#!/usr/bin/env python3
"""fullstack-director-vendor — vendor the framework into consumer repos (and this repo's own Claude bridge).

One command does placement + filtering + provenance — no content templating (SKILL.md is cross-harness portable;
see _artifacts/wsb-vendor-research.md). One canonical `.agents/skills/` emission serves Codex CLI + Gemini CLI
natively; a byte-identical `.claude/skills/` copy serves Claude Code. A per-file SHA-256 manifest (EOL-normalized)
makes local modification and upstream drift pure hash comparisons — the Spec-Kit/cruft pattern.

    python tools/vendor.py sync  --target <consumer-root> [--force]   # vendor/refresh a consumer
    python tools/vendor.py sync  --self                                # OPTIONAL local .claude/skills bridge —
                                                                       #   the master gitignores it (no committed
                                                                       #   bridge: skills auto-trigger and pollute
                                                                       #   framework-dev sessions; 2026-07-12)
    python tools/vendor.py check --target <consumer-root> | --self     # read-only drift detection (exit 1 on drift)
    python tools/vendor.py --self-test                                  # hermetic cases 1-9 + real-tree emission (10)

Exit codes: sync 0 ok / 2 locally-modified files skipped (list printed; --force overwrites) · check 0 clean /
1 drift (every file named). The manifest is `.director/vendor-manifest.json` at the target root. Vendored files
are never edited in a consumer — fixes flow master-first (shared/feedback-loop.md).

Stdlib only, Python 3.8+.
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

try:  # keep prints from crashing a legacy (cp1252) Windows console
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

GENERATOR = "fullstack-director-vendor"
GENERATOR_VERSION = "1.0.0"

SEATS = ["00-discovery", "01-planner", "02-designer", "03-architect", "04-builder",
         "05-reviewer", "06-release", "07-security", "08-refactor", "status",
         "feedback"]   # the capture half of the dogfood loop (shared/feedback-loop.md § Activation)
RUNTIME_DIRS = ("references", "templates")          # + SKILL.md; never evals/ (the runtime set — locked)
EXCLUDE_NAMES = {"evals", "__pycache__"}
AGENTS_FILES = ["fsd-reviewer.md", "fsd-reconciler.md", "fsd-owasp-reader.md"]
LEDGER_DEST = "docs/framework-feedback.md"
MANIFEST_DEST = ".director/vendor-manifest.json"
SKILL_ROOTS = (".agents/skills", ".claude/skills")   # the two managed skill roots (README + .gitattributes each)

LEDGER_SEED = """# Framework feedback ledger — dogfood findings for fullstack-director

> Append-only, SHA-stamped, immutable entries (supersede, never edit; never summarize). The contract — capture
> fields, upstream-first rule, triage dispositions — is `shared/feedback-loop.md`. `framework:` = `source_commit`
> from `.director/vendor-manifest.json`.

<!-- template — copy per finding:

### FB-NNN · <date> · <one-line title>
- **framework:** <source_commit from .director/vendor-manifest.json>
- **harness:** claude-code | codex | gemini-cli
- **seat:** <00-discovery … status | shared | vendor>
- **severity:** blocks-gate | wrong-but-recoverable | friction-only
- **expected:** <what the framework/skill should have done>
- **actual:** <what happened>
- **repro:** <minimal steps / the command>
- **artifact:** <path to transcript/diff/spine file>
- **status:** open | superseded-by FB-NNN | resolved-in <master sha>
-->
"""

ROOT_README = """# Vendored — fullstack-director skills (DO NOT EDIT)

Generated by `{generator}` {version}. Source: {repo} @ {commit} ({ref}), vendored {when}.
Regenerate/upgrade: `python tools/vendor.py sync --target <this repo>` run from the framework checkout.
Local modifications are detected by hash (`vendor.py check`) and skipped by `sync` — fixes flow **master-first**
per `shared/feedback-loop.md`; do not patch these files here except as a ledgered emergency.
"""

GITATTRIBUTES = "* linguist-generated=true\n**/* linguist-generated=true\n"


def norm_hash(data):
    """sha256 over CRLF-normalized bytes — EOL-insensitive (the Windows-EOL grader-churn lesson)."""
    return "sha256:" + hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def hash_file(path):
    return norm_hash(Path(path).read_bytes())


def runtime_files(seat_dir):
    """Relative paths of a seat's runtime set: SKILL.md + references/** + templates/** (files only, excl. junk)."""
    seat_dir = Path(seat_dir)
    out = []
    if (seat_dir / "SKILL.md").is_file():
        out.append("SKILL.md")
    for sub in RUNTIME_DIRS:
        d = seat_dir / sub
        if not d.is_dir():
            continue
        for p in sorted(d.rglob("*")):
            if not p.is_file():
                continue
            rel = p.relative_to(seat_dir)
            if any(part in EXCLUDE_NAMES for part in rel.parts) or p.suffix == ".pyc":
                continue
            out.append(rel.as_posix())
    return out


def git_provenance(master):
    """(repo, commit, ref) — tolerant of a git-less environment ("unknown")."""
    def g(*args):
        try:
            p = subprocess.run(["git", "-C", str(master), *args], capture_output=True, text=True,
                               encoding="utf-8", errors="replace", timeout=30)
            return p.stdout.strip() if p.returncode == 0 and p.stdout.strip() else None
        except Exception:
            return None
    return (g("config", "--get", "remote.origin.url") or str(master),
            g("rev-parse", "HEAD") or "unknown",
            g("rev-parse", "--abbrev-ref", "HEAD") or "unknown")


def build_items(master, self_mode):
    """The EMIT map (locked, design §②) as manifest items with SOURCE hashes. Dir-items own their dest subtree;
    file-items ("agents"/"meta") own individual files; the "ledger" item is seed-only (no hash machinery)."""
    master = Path(master)
    items = []
    for seat in SEATS:
        src = master / ".agents" / "skills" / seat
        files = {rel: hash_file(src / rel) for rel in runtime_files(src)}
        if not files:
            continue  # a mini-master (self-test) may carry fewer seats
        if not self_mode:
            items.append({"name": seat, "kind": "skill", "source_path": ".agents/skills/%s" % seat,
                          "dest_path": ".agents/skills/%s" % seat, "files": files})
        items.append({"name": seat + "@claude", "kind": "skill", "source_path": ".agents/skills/%s" % seat,
                      "dest_path": ".claude/skills/%s" % seat, "files": files})
    if not self_mode:
        shared_src = master / "shared"
        files = {p.name: hash_file(p) for p in sorted(shared_src.glob("*.md"))} if shared_src.is_dir() else {}
        if files:
            items.append({"name": "shared", "kind": "shared", "source_path": "shared",
                          "dest_path": "shared", "files": files})
        agents = {f: hash_file(master / ".claude" / "agents" / f)
                  for f in AGENTS_FILES if (master / ".claude" / "agents" / f).is_file()}
        if agents:
            items.append({"name": "fsd-agents", "kind": "agents", "source_path": ".claude/agents",
                          "dest_path": ".claude/agents", "files": agents})
        items.append({"name": "feedback-ledger", "kind": "ledger", "source_path": "-",
                      "dest_path": LEDGER_DEST, "files": {}})
    return items


def read_manifest(target):
    p = Path(target) / MANIFEST_DEST
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def count_open_feedback(target):
    """Open FB entries in the consumer's ledger (`- **status:** open`), HTML comments stripped so the seeded
    template inside `<!-- … -->` never counts. The Loop-B nudge: sync/check surface this so triage happens
    (shared/feedback-loop.md § Activation)."""
    p = Path(target) / LEDGER_DEST
    if not p.is_file():
        return 0
    text = re.sub(r"<!--.*?-->", "", p.read_text(encoding="utf-8", errors="replace"), flags=re.S)
    return len(re.findall(r"(?im)^\s*-\s*\*\*status:\*\*\s*open\b", text))


def feedback_nudge(target, verb):
    n = count_open_feedback(target)
    if n:
        print("note: %d open framework-feedback entr%s in %s — triage in the master repo before the next "
              "re-vendor (shared/feedback-loop.md §3)%s"
              % (n, "ies" if n != 1 else "y", LEDGER_DEST,
                 "; this sync did NOT resolve them" if verb == "sync" else ""))
    return n


def _meta_files(self_mode):
    roots = [".claude/skills"] if self_mode else list(SKILL_ROOTS)
    out = []
    for r in roots:
        out += ["%s/README.md" % r, "%s/.gitattributes" % r]
    return out


def do_sync(master, target, self_mode, force):
    master, target = Path(master), Path(target)
    items = build_items(master, self_mode)
    prev = read_manifest(target)

    # Spec-Kit protection: a dest file whose hash differs from what WE last wrote is locally modified.
    modified = []
    if prev:
        for it in prev.get("items", []):
            if it.get("kind") == "ledger":
                continue                              # the ledger is SUPPOSED to change — exempt
            for rel, h in it.get("files", {}).items():
                dest = target / it["dest_path"] / rel
                if dest.is_file() and hash_file(dest) != h:
                    modified.append((dest.relative_to(target)).as_posix())
    if modified and not force:
        print("REFUSING to overwrite %d locally-modified vendored file(s) (see shared/feedback-loop.md §2):"
              % len(modified))
        for m in modified:
            print("  modified: %s" % m)
        print("Re-run with --force to overwrite, or resolve upstream-first. Nothing was changed.")
        return 2

    # Delete-and-recreate the managed trees (dir-items own their dest subtree; ledger untouched).
    for it in items:
        dest = target / it["dest_path"]
        if it["kind"] == "ledger":
            if not dest.is_file():
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(LEDGER_SEED, encoding="utf-8", newline="\n")
            continue
        if it["kind"] in ("skill", "shared"):
            if dest.exists():
                shutil.rmtree(dest)
            for rel in it["files"]:
                s, d = master / it["source_path"] / rel, dest / rel
                d.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(s, d)                 # byte copy — hashes stay canonical
        elif it["kind"] == "agents":
            dest.mkdir(parents=True, exist_ok=True)
            for rel in it["files"]:
                shutil.copyfile(master / it["source_path"] / rel, dest / rel)

    # Managed-root meta + manifest — rewritten only when the content set changed (true idempotence: a second
    # sync leaves every byte alone, timestamps included); missing meta files are always restored.
    changed = not (prev and prev.get("items") == items)
    repo, commit, ref = git_provenance(master)
    when = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    for rel in _meta_files(self_mode):
        p = target / rel
        if not changed and p.is_file():
            continue
        p.parent.mkdir(parents=True, exist_ok=True)
        body = GITATTRIBUTES if rel.endswith(".gitattributes") else ROOT_README.format(
            generator=GENERATOR, version=GENERATOR_VERSION, repo=repo, commit=commit, ref=ref, when=when)
        p.write_text(body, encoding="utf-8", newline="\n")
    if changed:
        manifest = {"generator": GENERATOR, "generator_version": GENERATOR_VERSION,
                    "source_repo": repo, "source_commit": commit, "source_ref": ref,
                    "vendored_at": when, "hash_normalization": "crlf-to-lf", "items": items}
        mp = target / MANIFEST_DEST
        mp.parent.mkdir(parents=True, exist_ok=True)
        tmp = mp.with_suffix(".tmp")
        tmp.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
        os.replace(tmp, mp)
    n = sum(len(it["files"]) for it in items)
    print("synced %d item(s), %d file(s) -> %s%s" % (
        len(items), n, target, " [--force overwrote %d local mod(s)]" % len(modified) if modified else ""))
    if not self_mode:
        feedback_nudge(target, "sync")
    return 0


def do_check(master, target, self_mode):
    master, target = Path(master), Path(target)
    manifest = read_manifest(target)
    if not manifest:
        print("DRIFT: no readable manifest at %s — never vendored (or manifest deleted)" % (target / MANIFEST_DEST))
        return 1
    consumer, upstream = [], []
    # (a) consumer drift — on-disk dest vs the manifest (what we last wrote).
    for it in manifest.get("items", []):
        if it.get("kind") == "ledger":
            continue
        for rel, h in it.get("files", {}).items():
            dest = target / it["dest_path"] / rel
            if not dest.is_file():
                consumer.append("missing: %s/%s" % (it["dest_path"], rel))
            elif hash_file(dest) != h:
                consumer.append("modified: %s/%s" % (it["dest_path"], rel))
    # (b) upstream drift — CURRENT canonical source vs the manifest (content hashes, never SHA comparison).
    # The ledger is seed-only on both sides of the comparison (it legitimately diverges).
    current = {(it["name"], it["kind"]): it for it in build_items(master, self_mode) if it.get("kind") != "ledger"}
    recorded = {(it["name"], it["kind"]): it for it in manifest.get("items", []) if it.get("kind") != "ledger"}
    for key, cur in current.items():
        old = recorded.get(key)
        if old is None:
            upstream.append("new item upstream: %s" % key[0])
            continue
        for rel, h in cur["files"].items():
            if old["files"].get(rel) != h:
                upstream.append("%s: %s/%s" % ("changed" if rel in old["files"] else "added", cur["source_path"], rel))
        for rel in old["files"]:
            if rel not in cur["files"]:
                upstream.append("removed upstream: %s/%s" % (cur["source_path"], rel))
    for key in recorded:
        if key not in current:
            upstream.append("item removed upstream: %s" % key[0])
    for label, rows in (("consumer-side drift (locally modified/missing)", consumer),
                        ("upstream drift (re-vendor needed)", upstream)):
        if rows:
            print("DRIFT — %s:" % label)
            for r in rows:
                print("  %s" % r)
    if not self_mode:
        feedback_nudge(target, "check")
    if not consumer and not upstream:
        print("clean: %d item(s) match the manifest and the canonical source" % len(recorded))
        return 0
    return 1


# ---------------------------------------------------------------- self-test (hermetic staged trees)

def _mini_master(root):
    """A fake framework checkout: 2 seats (one with a planted evals/ trap), shared/, one agents file, and the
    must-not-ship AGENTS.md/CLAUDE.md plants at root."""
    def w(rel, s="x\n"):
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(s, encoding="utf-8", newline="\n")
    w(".agents/skills/00-discovery/SKILL.md", "---\nname: 00-discovery\ndescription: d\n---\nbody\n")
    w(".agents/skills/00-discovery/references/a.md", "ref a\n")
    w(".agents/skills/00-discovery/templates/b.md", "tpl b\n")
    w(".agents/skills/00-discovery/evals/trap.py", "print('must not ship')\n")
    w(".agents/skills/status/SKILL.md", "---\nname: status\ndescription: d\n---\nbody\n")
    w("shared/x.md", "shared x\n")
    w("shared/y.md", "shared y\n")
    w(".claude/agents/fsd-reviewer.md", "---\nname: fsd-reviewer\n---\nbody\n")
    w("AGENTS.md", "LAYER A — must not ship\n")
    w("CLAUDE.md", "LAYER A — must not ship\n")
    try:
        subprocess.run(["git", "-C", str(root), "init", "-q"], capture_output=True, timeout=30)
        subprocess.run(["git", "-C", str(root), "add", "-A"], capture_output=True, timeout=30)
        subprocess.run(["git", "-C", str(root), "-c", "user.email=t@t", "-c", "user.name=t",
                        "commit", "-qm", "seed"], capture_output=True, timeout=30)
    except Exception:
        pass


def _tree_hashes(root, skip_top=(".director",)):
    out = {}
    root = Path(root)
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root).as_posix()
        if rel.split("/")[0] in skip_top or rel.split("/")[0] == ".git":
            continue
        out[rel] = hash_file(p)
    return out


def self_test():
    import tempfile
    rows, ok = [], True

    def case(name, good, note=""):
        nonlocal ok
        rows.append((name, good, note))
        ok = ok and good

    tmp = tempfile.mkdtemp(prefix="vendor-st-")
    try:
        master = Path(tmp) / "master"
        consumer = Path(tmp) / "consumer"
        master.mkdir(); consumer.mkdir()
        _mini_master(master)

        # 1 — ideal sync: EMIT map lands; no evals/ leak; AGENTS/CLAUDE absent; ledger seeded.
        rc = do_sync(master, consumer, self_mode=False, force=False)
        leaked = [str(p) for p in consumer.rglob("*") if "evals" in p.parts or p.name == "trap.py"]
        must = [".agents/skills/00-discovery/SKILL.md", ".agents/skills/00-discovery/references/a.md",
                ".claude/skills/00-discovery/templates/b.md", ".claude/skills/status/SKILL.md",
                "shared/x.md", ".claude/agents/fsd-reviewer.md", LEDGER_DEST, MANIFEST_DEST,
                ".agents/skills/README.md", ".claude/skills/.gitattributes"]
        missing = [m for m in must if not (consumer / m).is_file()]
        layer_a = [(consumer / f).is_file() for f in ("AGENTS.md", "CLAUDE.md")]
        seeded = "FB-NNN" in (consumer / LEDGER_DEST).read_text(encoding="utf-8")
        case("1 ideal sync (EMIT map; no evals/ leak; no Layer-A; ledger seeded)",
             rc == 0 and not leaked and not missing and not any(layer_a) and seeded,
             "rc=%s leaked=%s missing=%s layerA=%s" % (rc, leaked, missing, layer_a))

        # 2 — .agents ↔ .claude byte parity.
        a = _tree_hashes(consumer / ".agents" / "skills")
        c = _tree_hashes(consumer / ".claude" / "skills")
        case("2 .agents↔.claude byte parity", a == c and len(a) > 3, "a=%d c=%d" % (len(a), len(c)))

        # 3 — manifest hashes match disk; provenance sane.
        man = read_manifest(consumer)
        bad = []
        for it in man["items"]:
            if it["kind"] == "ledger":
                continue
            for rel, h in it["files"].items():
                if hash_file(consumer / it["dest_path"] / rel) != h:
                    bad.append("%s/%s" % (it["dest_path"], rel))
        sha_ok = man["source_commit"] == "unknown" or len(man["source_commit"]) == 40
        case("3 manifest hashes == disk; source_commit sane", man is not None and not bad and sha_ok,
             "bad=%s sha=%s" % (bad, man["source_commit"][:12]))

        # 4 — idempotence: second sync changes nothing (manifest incl.).
        before = _tree_hashes(consumer, skip_top=())
        rc2 = do_sync(master, consumer, self_mode=False, force=False)
        case("4 second sync is a no-op", rc2 == 0 and _tree_hashes(consumer, skip_top=()) == before, "rc=%s" % rc2)

        # 5 — local-mod protection: skip+report (exit 2), untouched; --force restores canonical.
        victim = consumer / ".claude" / "skills" / "00-discovery" / "SKILL.md"
        victim.write_text("consumer hand-edit\n", encoding="utf-8")
        rc5 = do_sync(master, consumer, self_mode=False, force=False)
        untouched = victim.read_text(encoding="utf-8") == "consumer hand-edit\n"
        rc5f = do_sync(master, consumer, self_mode=False, force=True)
        restored = "consumer hand-edit" not in victim.read_text(encoding="utf-8")
        case("5 local-mod: sync exits 2 + untouched; --force restores",
             rc5 == 2 and untouched and rc5f == 0 and restored,
             "rc=%s untouched=%s force_rc=%s restored=%s" % (rc5, untouched, rc5f, restored))

        # 6 — check: consumer drift → exit 1 naming the file; restore → 0.
        victim.write_text("drift\n", encoding="utf-8")
        rc6 = do_check(master, consumer, self_mode=False)
        do_sync(master, consumer, self_mode=False, force=True)
        rc6b = do_check(master, consumer, self_mode=False)
        case("6 check bites on consumer drift, clean after restore", rc6 == 1 and rc6b == 0,
             "drift_rc=%s clean_rc=%s" % (rc6, rc6b))

        # 7 — check: upstream drift → exit 1.
        (master / ".agents" / "skills" / "status" / "SKILL.md").write_text(
            "---\nname: status\ndescription: CHANGED upstream\n---\nbody\n", encoding="utf-8", newline="\n")
        rc7 = do_check(master, consumer, self_mode=False)
        case("7 check bites on upstream drift", rc7 == 1, "rc=%s" % rc7)

        # 8 — ledger immunity + the open-entry counter: the seeded template never counts (comments stripped);
        #     an appended open entry counts 1 and survives a re-sync.
        ledger = consumer / LEDGER_DEST
        n_fresh = count_open_feedback(consumer)
        ledger.write_text(ledger.read_text(encoding="utf-8") + "\n### FB-001 · test\n- **status:** open\n",
                          encoding="utf-8")
        n_open = count_open_feedback(consumer)
        do_sync(master, consumer, self_mode=False, force=True)
        case("8 ledger survives re-sync; open-entry counter: template=0, appended-open=1",
             "FB-001" in ledger.read_text(encoding="utf-8") and n_fresh == 0 and n_open == 1
             and count_open_feedback(consumer) == 1,
             "fresh=%d open=%d post-sync=%d" % (n_fresh, n_open, count_open_feedback(consumer)))

        # 9 — --self mode: only the .claude bridge + manifest (no shared/agents/ledger items).
        selfc = Path(tmp) / "selfmaster"
        shutil.copytree(master, selfc, ignore=shutil.ignore_patterns(".git"))
        rc9 = do_sync(selfc, selfc, self_mode=True, force=False)
        man9 = read_manifest(selfc)
        kinds = sorted({it["kind"] for it in man9["items"]})
        bridge = (selfc / ".claude" / "skills" / "00-discovery" / "SKILL.md").is_file()
        no_extra = not (selfc / LEDGER_DEST).is_file()
        rc9c = do_check(selfc, selfc, self_mode=True)
        case("9 --self: bridge+manifest only; check --self clean",
             rc9 == 0 and kinds == ["skill"] and bridge and no_extra and rc9c == 0,
             "kinds=%s rc=%s check=%s" % (kinds, rc9, rc9c))

        # 10 — REAL-tree emission: sync THIS repo into a temp consumer and assert the full EMIT map on the true
        #      content (the standing guard that replaced the master's committed bridge — decision 2026-07-12:
        #      the master commits no bridge; this proves every real seat vendors cleanly for consumers).
        real_master = Path(__file__).resolve().parent.parent
        if (real_master / ".agents" / "skills" / "00-discovery" / "SKILL.md").is_file():
            realc = Path(tmp) / "real-consumer"
            realc.mkdir()
            rc10 = do_sync(real_master, realc, self_mode=False, force=False)
            seats_a = sorted(p.name for p in (realc / ".agents" / "skills").iterdir() if p.is_dir())
            seats_c = sorted(p.name for p in (realc / ".claude" / "skills").iterdir() if p.is_dir())
            parity10 = _tree_hashes(realc / ".agents" / "skills") == _tree_hashes(realc / ".claude" / "skills")
            leak10 = [str(p) for p in realc.rglob("*") if "evals" in p.parts]
            fsd10 = all((realc / ".claude" / "agents" / f).is_file() for f in AGENTS_FILES)
            shared10 = (realc / "shared" / "feedback-loop.md").is_file()
            layer_a10 = any((realc / f).is_file() for f in ("AGENTS.md", "CLAUDE.md"))
            case("10 real-tree emission (this repo → temp consumer)",
                 rc10 == 0 and seats_a == sorted(SEATS) and seats_a == seats_c and parity10
                 and not leak10 and fsd10 and shared10 and not layer_a10,
                 "rc=%s seats=%d/%d parity=%s leak=%s fsd=%s shared=%s layerA=%s" % (
                     rc10, len(seats_a), len(SEATS), parity10, len(leak10), fsd10, shared10, layer_a10))
        else:
            case("10 real-tree emission (this repo → temp consumer)", True,
                 "skipped — not running from a framework checkout")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    w = max(len(r[0]) for r in rows)
    print("\n== vendor.py self-test (hermetic staged trees) ==")
    for name, good, note in rows:
        print("  [%s] %s  %s" % ("PASS" if good else "FAIL", name.ljust(w), note if not good else ""))
    print("\n%s" % ("ALL GOOD — vendor.py is sound (emits right, protects local mods, bites on drift)"
                    if ok else "SELF-TEST FAILED"))
    return 0 if ok else 1


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if "--self-test" in argv:
        return self_test()
    ap = argparse.ArgumentParser(description="Vendor the fullstack-director framework (sync/check).")
    ap.add_argument("command", choices=["sync", "check"])
    ap.add_argument("--target", help="consumer repo root")
    ap.add_argument("--self", dest="self_mode", action="store_true",
                    help="operate on this repo's own .claude/skills bridge")
    ap.add_argument("--force", action="store_true", help="overwrite locally-modified vendored files")
    a = ap.parse_args(argv)
    master = Path(__file__).resolve().parent.parent
    if a.self_mode:
        target = master
    elif a.target:
        target = Path(a.target).resolve()
    else:
        ap.error("--target <consumer-root> or --self is required")
    if a.command == "sync":
        return do_sync(master, target, a.self_mode, a.force)
    return do_check(master, target, a.self_mode)


if __name__ == "__main__":
    sys.exit(main())
